analyzer:
  exclude:
    - build/**

linter:
  rules:
    always_use_package_imports: true
    avoid_print: true
    avoid_relative_lib_imports: true
    directives_ordering: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    use_super_parameters: true
